### ISSUE TITLE
Errors when loading into Glyphs

### ISSUE THREAD

**Issue by gingerbeardman** [DrTypo/sapperlot#3]
I think there have been breaking changes since this was made?

<img width="670" alt="Screen shot 2020-11-23 at 16 42 49" src="https://user-images.githubusercontent.com/49612/99989837-02872180-2dab-11eb-85d6-5aa66400171e.png">

**Comment by DrTypo** [comment]
you have to keep everything

(button on the right)

________________________________
Von: Matt Sephton <notifications@github.com>
Gesendet: Montag, 23. November 2020 17:43:50
An: DrTypo/sapperlot
Cc: Subscribed
Betreff: [DrTypo/sapperlot] Errors when loading into Glyphs (#3)


I think there have been breaking changes since this was made?

[Screen shot 2020-11-23 at 16 42 49]<https://user-images.githubusercontent.com/49612/99989837-02872180-2dab-11eb-85d6-5aa66400171e.png>

**Comment by gingerbeardman** [comment]
Thanks!

I'm trying to learn from your font to make a simple layered font of my own.
